version: '2'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden-restaurar
    environment:
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
    volumes:
      - /mnt/appdata/docker/vaultwarden:/data
    ports:
      - 90:80
      - 3012:3012
    restart: always
