version: '2'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    environment:
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
    volumes:
      - /mnt/appdata/docker/vaultwarden:/data # El directorio donde se creara la base de datos
    ports:
      - 88:80
      - 3012:3012
    restart: always

  db-backup:
    container_name: db-backup
    image: tiredofit/db-backup
    links:
     - vaultwarden
    volumes:
      - /mnt/appdata/docker/vaultwarden:/backup # El directorio donde esta la base de datos, igual que en vaultwarden
      - /mnt/appdata/docker/vaultwarden/post-script.sh:/assets/custom-scripts/post-script.sh 
    environment:
      - DB_TYPE=sqlite3 # tipo de db, lo usual es sqlite
      - DB_HOST=/backup/db.sqlite3 # la ruta exacta de la base de datos, se deja tal cual
      - DB_NAME=database # igual
      - DB_USER=root # igual
      - DB_DUMP_FREQ=1440 # la frecuencia en minutos con la que se hara la copia. 1440 es una vez al dia
#      - DB_DUMP_BEGIN=0000 # Aqui podemos señalar la hora a la que queramos que empiece a hacerse, formato hh:mm sin el :
      - DB_CLEANUP_TIME=8640 # Cada cuantos dias queremos borrar 
      - MD5=TRUE 
      - COMPRESSION=GZ
      - SPLIT_DB=FALSE
      - BACKUP_LOCATION=FILESYSTEM
    restart: always
